adding the models
this-is-not-a-org/monetarium pull request #8
Opened 2021-03-31 14:45 UTC by lucaslima18

Estas models ainda estão em fase inicial, mas a base é esta

2021-03-31 14:50 UTC, lucaslima18 reviewed
as modificações foram feitas

2021-03-31 15:02 UTC, markirius requested changes

2021-03-31 15:02 UTC, markirius commented on apps/financial/models.py
> +        ('DV', 'Dívida'),
use english language, in another moment, we will use a translation builltin django method

2021-03-31 15:02 UTC, markirius commented on apps/financial/models.py
> +        ('CR', 'Crédito'),
use english language here too  and all another text stuff too

2021-03-31 15:03 UTC, markirius requested changes
check notes on review

2021-03-31 15:56 UTC, lucaslima18 commented on apps/financial/models.py
> +        ('DV', 'Dívida'),
okey, i will fix that

2021-04-01 19:27 UTC, markirius requested changes

2021-04-01 19:27 UTC, markirius commented on apps/financial/models.py
> +    valor = models.DecimalField(max_digits=20, decimal_places=2)
isn't **value** instead **valor**?

2021-04-01 19:27 UTC, markirius commented on apps/financial/models.py
> +    valor = models.DecimalField(max_digits=20, decimal_places=2)
same issue here.

2021-04-01 19:27 UTC, markirius commented on apps/financial/models.py
> +        ('CD', 'Card debt'),
debit?

2021-04-02 04:49 UTC, lucaslima18 commented on apps/financial/models.py
> +        ('CD', 'Card debt'),
debt == dívida

2021-04-02 04:49 UTC, lucaslima18 commented on apps/financial/models.py
> +        ('CD', 'Card debt'),
debit == débito

2021-04-02 08:09 UTC, markirius approved these changes

2021-04-02 08:10 UTC, merged